### ISSUE TITLE
ZJSON install issue

### ISSUE THREAD

**Issue by bryansippel** [se38/zJSON#19] opened 2016-02-09 17:46 UTC
I am trying to install ZJSON so I can do REST services via ABAP. 

I believe I have upgraded to the newest ZSAPLINK_INSTALL and I am trying to run ZSAPLINK from SE38 to install the SAPlink_Daily.nugg file but I get the error "Plugin for object type MSAG is not installed on this system.

I have installed the SAPlink-plugins_Daily.nugg, but that did not install the MSAG plugin.

Is the plugin specific to ABAP for Eclipse? We are using ABAP via the SAPGui, not Eclipse. Do I need to install this?

Is there a step-by-step manual for preparing our system to use these ZJSON functions?

Any assistance would be greatly appreciated.

**Comment by se38** [comment] 2016-02-09 18:20
Hi Bryan,
Did you activate all inactive objects after the installation of the plugins?
Uwe

**Comment by gregorwolf** [comment] 2016-02-09 18:24
Also have you installed the plugins from http://plugins.SAPlink.org?

**Comment by bryansippel** [comment] 2016-02-09 19:30
I believe I have activated all of the inactive objects after installing the SAPlink-plugins_Daily.nugg file.

I have reviewed the http://plugins.SAPlink.org page which redirected me to https://www.assembla.com/spaces/saplink-plugins/wiki where I didn't see anything specific to MSAG so I clicked the "SAPlink plugin list wiki page" link and I saw the "SAPlink Plugins" section
"Download SAPlink Nugget containing all SAPlink-plugins from Code Exchange" link which took me back to the https://www.assembla.com/spaces/saplink-plugins/wiki page so I'm a bit confused.

**Comment by gregorwolf** [comment] 2016-02-09 19:44
Read the instructions on the wiki page and download the plugins nugget.

**Comment by bryansippel** [comment] 2016-02-09 20:34
For some reason, trying to select my downloaded SAPLink-plugins_Daily.nugg file from the dropdown in ZSAPLINK was instead selecting my other downloaded file SAPlink_Daily.nugg.

Once I copied and pasted the correct file into the input field, it loaded the plugin nugg, but now that I'm going through and activating everything, I am getting a syntax error on class ZSAPLINK_TABLE_TYPES, method CREATEIXMLDOCFROMOBJECT, line 29, saying type DD43V is unknown.

This is a standard field. Why would it not exist in our system? What version of SAP is ZJSON written for?

**Comment by gregorwolf** [comment] 2016-02-09 20:39
Have you installed the Plugins downloaded fromhttps://www.assembla.com/spaces/saplink-plugins/subversion/source/HEAD/build? What NetWeaver Release do you use?

**Comment by bryansippel** [comment] 2016-02-09 20:51
That is exactly the page I am currently looking at and I see a SAPlink-plugins_Daily.nugg and .zip file. I downloaded the nugg file and imported it using ZSAPLINK via SE38 and when activating all the objects, I got the compile error referencing the missing type DD43V.

We are on SAP_BASIS version 701 which I believe equates to NetWeaver 7.0 EP1 SP3.

**Comment by gregorwolf** [comment] 2016-02-09 22:00
As this is not a bug in zJSON please raise the issue in the SAPlink plugins project.

**Comment by gregorwolf** [comment] 2016-02-09 22:03
And I hope that you're not on SP3 which would mean that the system was never updated since January 22nd, 2009. The current SPS is 16. Please provide the detailed version information from System -> Status when you raise the issue.

**Comment by bryansippel** [comment] 2016-02-09 22:09
Clarification is a good thing!
Apparently we are on NetWeaver 7.0, EHP 1, SP 17. I was also told to say ECC 6.0 EHP 4. 
I'm just a developer. The version thing gets me every time. I just want them to all play nicely together.

**Comment by bryansippel** [comment] 2016-02-09 22:24
I don't see a place to post an issue or comment anywhere on the SAPlink plugins project page. Where do I go to do that?

**Comment by bryansippel** [comment] 2016-02-09 22:57
Nevermind. I just created a local type in the class. Thanks.

**Comment by se38** [comment] 2016-02-10 10:44
Has the import worked now correctly? Can I close this ticket?

**Comment by bryansippel** [comment] 2016-02-10 17:13
Once I created the local type, I was able to execute the install and activation. We must be on an older version. You can close the ticket. Thanks.

**Closed** 2016-02-10 17:13 UTC
